window.esdocSearchIndex = [
  [
    "heroiclabs-sdk-web/src/request.js~accountsrequest",
    "class/src/request.js~AccountsRequest.html",
    "<span>AccountsRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/request.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/achievement.js~achievementlistrequest",
    "class/src/achievement.js~AchievementListRequest.html",
    "<span>AchievementListRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/achievement.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/achievement.js~achievementupdaterequest",
    "class/src/achievement.js~AchievementUpdateRequest.html",
    "<span>AchievementUpdateRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/achievement.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/request.js~apirequest",
    "class/src/request.js~ApiRequest.html",
    "<span>ApiRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/request.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_check.js~checkanonymousrequest",
    "class/src/account_check.js~CheckAnonymousRequest.html",
    "<span>CheckAnonymousRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_check.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_check.js~checkemailrequest",
    "class/src/account_check.js~CheckEmailRequest.html",
    "<span>CheckEmailRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_check.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_check.js~checkfacebookrequest",
    "class/src/account_check.js~CheckFacebookRequest.html",
    "<span>CheckFacebookRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_check.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_check.js~checkgooglerequest",
    "class/src/account_check.js~CheckGoogleRequest.html",
    "<span>CheckGoogleRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_check.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_check.js~checkrequest",
    "class/src/account_check.js~CheckRequest.html",
    "<span>CheckRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_check.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_check.js~checktangorequest",
    "class/src/account_check.js~CheckTangoRequest.html",
    "<span>CheckTangoRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_check.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/client.js~client",
    "class/src/client.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/client.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_login.js~createemailrequest",
    "class/src/account_login.js~CreateEmailRequest.html",
    "<span>CreateEmailRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_login.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_login.js~emailpasswordresetrequest",
    "class/src/account_login.js~EmailPasswordResetRequest.html",
    "<span>EmailPasswordResetRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_login.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/script.js~executescriptrequest",
    "class/src/script.js~ExecuteScriptRequest.html",
    "<span>ExecuteScriptRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/script.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/game.js~gamegetrequest",
    "class/src/game.js~GameGetRequest.html",
    "<span>GameGetRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/game.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/gamer.js~gamergetrequest",
    "class/src/gamer.js~GamerGetRequest.html",
    "<span>GamerGetRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/gamer.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/gamer.js~gamerupdaterequest",
    "class/src/gamer.js~GamerUpdateRequest.html",
    "<span>GamerUpdateRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/gamer.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/leaderboard.js~leaderboardandrankgetrequest",
    "class/src/leaderboard.js~LeaderboardAndRankGetRequest.html",
    "<span>LeaderboardAndRankGetRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/leaderboard.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/leaderboard.js~leaderboardgetrequest",
    "class/src/leaderboard.js~LeaderboardGetRequest.html",
    "<span>LeaderboardGetRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/leaderboard.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/leaderboard.js~leaderboardlistrequest",
    "class/src/leaderboard.js~LeaderboardListRequest.html",
    "<span>LeaderboardListRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/leaderboard.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/leaderboard.js~leaderboardupdaterequest",
    "class/src/leaderboard.js~LeaderboardUpdateRequest.html",
    "<span>LeaderboardUpdateRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/leaderboard.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_link.js~linkanonymousrequest",
    "class/src/account_link.js~LinkAnonymousRequest.html",
    "<span>LinkAnonymousRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_link.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_link.js~linkfacebookrequest",
    "class/src/account_link.js~LinkFacebookRequest.html",
    "<span>LinkFacebookRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_link.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_link.js~linkgooglerequest",
    "class/src/account_link.js~LinkGoogleRequest.html",
    "<span>LinkGoogleRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_link.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_link.js~linkrequest",
    "class/src/account_link.js~LinkRequest.html",
    "<span>LinkRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_link.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_link.js~linktangorequest",
    "class/src/account_link.js~LinkTangoRequest.html",
    "<span>LinkTangoRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_link.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_login.js~loginanonymousrequest",
    "class/src/account_login.js~LoginAnonymousRequest.html",
    "<span>LoginAnonymousRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_login.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_login.js~loginemailrequest",
    "class/src/account_login.js~LoginEmailRequest.html",
    "<span>LoginEmailRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_login.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_login.js~loginfacebookrequest",
    "class/src/account_login.js~LoginFacebookRequest.html",
    "<span>LoginFacebookRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_login.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_login.js~logingooglerequest",
    "class/src/account_login.js~LoginGoogleRequest.html",
    "<span>LoginGoogleRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_login.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_login.js~loginrequest",
    "class/src/account_login.js~LoginRequest.html",
    "<span>LoginRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_login.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_login.js~logintangorequest",
    "class/src/account_login.js~LoginTangoRequest.html",
    "<span>LoginTangoRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_login.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/match.js~matchcreaterequest",
    "class/src/match.js~MatchCreateRequest.html",
    "<span>MatchCreateRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/match.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/match.js~matchgetrequest",
    "class/src/match.js~MatchGetRequest.html",
    "<span>MatchGetRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/match.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/match.js~matchlistrequest",
    "class/src/match.js~MatchListRequest.html",
    "<span>MatchListRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/match.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/match.js~matchmakerequest",
    "class/src/match.js~MatchMakeRequest.html",
    "<span>MatchMakeRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/match.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/match.js~matchturnendrequest",
    "class/src/match.js~MatchTurnEndRequest.html",
    "<span>MatchTurnEndRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/match.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/match.js~matchturngetrequest",
    "class/src/match.js~MatchTurnGetRequest.html",
    "<span>MatchTurnGetRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/match.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/match.js~matchturnleaverequest",
    "class/src/match.js~MatchTurnLeaveRequest.html",
    "<span>MatchTurnLeaveRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/match.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/match.js~matchturnsubmitrequest",
    "class/src/match.js~MatchTurnSubmitRequest.html",
    "<span>MatchTurnSubmitRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/match.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/match.js~matchessincerequest",
    "class/src/match.js~MatchesSinceRequest.html",
    "<span>MatchesSinceRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/match.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/message.js~messagedeleterequest",
    "class/src/message.js~MessageDeleteRequest.html",
    "<span>MessageDeleteRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/message.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/message.js~messagelistrequest",
    "class/src/message.js~MessageListRequest.html",
    "<span>MessageListRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/message.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/message.js~messagereadrequest",
    "class/src/message.js~MessageReadRequest.html",
    "<span>MessageReadRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/message.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/ping.js~pingrequest",
    "class/src/ping.js~PingRequest.html",
    "<span>PingRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/ping.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/request.js~request",
    "class/src/request.js~Request.html",
    "<span>Request</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/request.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/client.js~response",
    "class/src/client.js~Response.html",
    "<span>Response</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/client.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/server.js~serverrequest",
    "class/src/server.js~ServerRequest.html",
    "<span>ServerRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/server.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/session.js~session",
    "class/src/session.js~Session.html",
    "<span>Session</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/session.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/shared_storage.js~sharedstoragedeleterequest",
    "class/src/shared_storage.js~SharedStorageDeleteRequest.html",
    "<span>SharedStorageDeleteRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/shared_storage.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/shared_storage.js~sharedstoragegetrequest",
    "class/src/shared_storage.js~SharedStorageGetRequest.html",
    "<span>SharedStorageGetRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/shared_storage.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/shared_storage.js~sharedstoragepatchrequest",
    "class/src/shared_storage.js~SharedStoragePatchRequest.html",
    "<span>SharedStoragePatchRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/shared_storage.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/shared_storage.js~sharedstorageputrequest",
    "class/src/shared_storage.js~SharedStoragePutRequest.html",
    "<span>SharedStoragePutRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/shared_storage.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/shared_storage.js~sharedstoragesearchrequest",
    "class/src/shared_storage.js~SharedStorageSearchRequest.html",
    "<span>SharedStorageSearchRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/shared_storage.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/storage.js~storagedeleterequest",
    "class/src/storage.js~StorageDeleteRequest.html",
    "<span>StorageDeleteRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/storage.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/storage.js~storagegetrequest",
    "class/src/storage.js~StorageGetRequest.html",
    "<span>StorageGetRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/storage.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/storage.js~storageputrequest",
    "class/src/storage.js~StoragePutRequest.html",
    "<span>StoragePutRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/storage.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_unlink.js~unlinkanonymousrequest",
    "class/src/account_unlink.js~UnlinkAnonymousRequest.html",
    "<span>UnlinkAnonymousRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_unlink.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_unlink.js~unlinkemailrequest",
    "class/src/account_unlink.js~UnlinkEmailRequest.html",
    "<span>UnlinkEmailRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_unlink.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_unlink.js~unlinkfacebookrequest",
    "class/src/account_unlink.js~UnlinkFacebookRequest.html",
    "<span>UnlinkFacebookRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_unlink.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_unlink.js~unlinkgooglerequest",
    "class/src/account_unlink.js~UnlinkGoogleRequest.html",
    "<span>UnlinkGoogleRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_unlink.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_unlink.js~unlinkrequest",
    "class/src/account_unlink.js~UnlinkRequest.html",
    "<span>UnlinkRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_unlink.js</span>",
    "class"
  ],
  [
    "heroiclabs-sdk-web/src/account_unlink.js~unlinktangorequest",
    "class/src/account_unlink.js~UnlinkTangoRequest.html",
    "<span>UnlinkTangoRequest</span> <span class=\"search-result-import-path\">heroiclabs-sdk-web/src/account_unlink.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/account_check.js",
    "file/src/account_check.js.html",
    "src/account_check.js",
    "file"
  ],
  [
    "src/account_check.js~checkanonymousrequest#constructor",
    "class/src/account_check.js~CheckAnonymousRequest.html#instance-constructor-constructor",
    "src/account_check.js~CheckAnonymousRequest#constructor",
    "method"
  ],
  [
    "src/account_check.js~checkanonymousrequest#session",
    "class/src/account_check.js~CheckAnonymousRequest.html#instance-method-session",
    "src/account_check.js~CheckAnonymousRequest#session",
    "method"
  ],
  [
    "src/account_check.js~checkemailrequest#constructor",
    "class/src/account_check.js~CheckEmailRequest.html#instance-constructor-constructor",
    "src/account_check.js~CheckEmailRequest#constructor",
    "method"
  ],
  [
    "src/account_check.js~checkemailrequest#session",
    "class/src/account_check.js~CheckEmailRequest.html#instance-method-session",
    "src/account_check.js~CheckEmailRequest#session",
    "method"
  ],
  [
    "src/account_check.js~checkfacebookrequest#constructor",
    "class/src/account_check.js~CheckFacebookRequest.html#instance-constructor-constructor",
    "src/account_check.js~CheckFacebookRequest#constructor",
    "method"
  ],
  [
    "src/account_check.js~checkgooglerequest#constructor",
    "class/src/account_check.js~CheckGoogleRequest.html#instance-constructor-constructor",
    "src/account_check.js~CheckGoogleRequest#constructor",
    "method"
  ],
  [
    "src/account_check.js~checkrequest#constructor",
    "class/src/account_check.js~CheckRequest.html#instance-constructor-constructor",
    "src/account_check.js~CheckRequest#constructor",
    "method"
  ],
  [
    "src/account_check.js~checkrequest#session",
    "class/src/account_check.js~CheckRequest.html#instance-method-session",
    "src/account_check.js~CheckRequest#session",
    "method"
  ],
  [
    "src/account_check.js~checktangorequest#constructor",
    "class/src/account_check.js~CheckTangoRequest.html#instance-constructor-constructor",
    "src/account_check.js~CheckTangoRequest#constructor",
    "method"
  ],
  [
    "src/account_link.js",
    "file/src/account_link.js.html",
    "src/account_link.js",
    "file"
  ],
  [
    "src/account_link.js~linkanonymousrequest#constructor",
    "class/src/account_link.js~LinkAnonymousRequest.html#instance-constructor-constructor",
    "src/account_link.js~LinkAnonymousRequest#constructor",
    "method"
  ],
  [
    "src/account_link.js~linkfacebookrequest#constructor",
    "class/src/account_link.js~LinkFacebookRequest.html#instance-constructor-constructor",
    "src/account_link.js~LinkFacebookRequest#constructor",
    "method"
  ],
  [
    "src/account_link.js~linkgooglerequest#constructor",
    "class/src/account_link.js~LinkGoogleRequest.html#instance-constructor-constructor",
    "src/account_link.js~LinkGoogleRequest#constructor",
    "method"
  ],
  [
    "src/account_link.js~linkrequest#constructor",
    "class/src/account_link.js~LinkRequest.html#instance-constructor-constructor",
    "src/account_link.js~LinkRequest#constructor",
    "method"
  ],
  [
    "src/account_link.js~linktangorequest#constructor",
    "class/src/account_link.js~LinkTangoRequest.html#instance-constructor-constructor",
    "src/account_link.js~LinkTangoRequest#constructor",
    "method"
  ],
  [
    "src/account_login.js",
    "file/src/account_login.js.html",
    "src/account_login.js",
    "file"
  ],
  [
    "src/account_login.js~createemailrequest#constructor",
    "class/src/account_login.js~CreateEmailRequest.html#instance-constructor-constructor",
    "src/account_login.js~CreateEmailRequest#constructor",
    "method"
  ],
  [
    "src/account_login.js~createemailrequest#name",
    "class/src/account_login.js~CreateEmailRequest.html#instance-method-name",
    "src/account_login.js~CreateEmailRequest#name",
    "method"
  ],
  [
    "src/account_login.js~createemailrequest#nickname",
    "class/src/account_login.js~CreateEmailRequest.html#instance-method-nickname",
    "src/account_login.js~CreateEmailRequest#nickname",
    "method"
  ],
  [
    "src/account_login.js~createemailrequest#session",
    "class/src/account_login.js~CreateEmailRequest.html#instance-method-session",
    "src/account_login.js~CreateEmailRequest#session",
    "method"
  ],
  [
    "src/account_login.js~emailpasswordresetrequest#constructor",
    "class/src/account_login.js~EmailPasswordResetRequest.html#instance-constructor-constructor",
    "src/account_login.js~EmailPasswordResetRequest#constructor",
    "method"
  ],
  [
    "src/account_login.js~loginanonymousrequest#constructor",
    "class/src/account_login.js~LoginAnonymousRequest.html#instance-constructor-constructor",
    "src/account_login.js~LoginAnonymousRequest#constructor",
    "method"
  ],
  [
    "src/account_login.js~loginanonymousrequest#session",
    "class/src/account_login.js~LoginAnonymousRequest.html#instance-method-session",
    "src/account_login.js~LoginAnonymousRequest#session",
    "method"
  ],
  [
    "src/account_login.js~loginemailrequest#constructor",
    "class/src/account_login.js~LoginEmailRequest.html#instance-constructor-constructor",
    "src/account_login.js~LoginEmailRequest#constructor",
    "method"
  ],
  [
    "src/account_login.js~loginemailrequest#session",
    "class/src/account_login.js~LoginEmailRequest.html#instance-method-session",
    "src/account_login.js~LoginEmailRequest#session",
    "method"
  ],
  [
    "src/account_login.js~loginfacebookrequest#constructor",
    "class/src/account_login.js~LoginFacebookRequest.html#instance-constructor-constructor",
    "src/account_login.js~LoginFacebookRequest#constructor",
    "method"
  ],
  [
    "src/account_login.js~logingooglerequest#constructor",
    "class/src/account_login.js~LoginGoogleRequest.html#instance-constructor-constructor",
    "src/account_login.js~LoginGoogleRequest#constructor",
    "method"
  ],
  [
    "src/account_login.js~loginrequest#constructor",
    "class/src/account_login.js~LoginRequest.html#instance-constructor-constructor",
    "src/account_login.js~LoginRequest#constructor",
    "method"
  ],
  [
    "src/account_login.js~loginrequest#session",
    "class/src/account_login.js~LoginRequest.html#instance-method-session",
    "src/account_login.js~LoginRequest#session",
    "method"
  ],
  [
    "src/account_login.js~logintangorequest#constructor",
    "class/src/account_login.js~LoginTangoRequest.html#instance-constructor-constructor",
    "src/account_login.js~LoginTangoRequest#constructor",
    "method"
  ],
  [
    "src/account_unlink.js",
    "file/src/account_unlink.js.html",
    "src/account_unlink.js",
    "file"
  ],
  [
    "src/account_unlink.js~unlinkanonymousrequest#constructor",
    "class/src/account_unlink.js~UnlinkAnonymousRequest.html#instance-constructor-constructor",
    "src/account_unlink.js~UnlinkAnonymousRequest#constructor",
    "method"
  ],
  [
    "src/account_unlink.js~unlinkemailrequest#constructor",
    "class/src/account_unlink.js~UnlinkEmailRequest.html#instance-constructor-constructor",
    "src/account_unlink.js~UnlinkEmailRequest#constructor",
    "method"
  ],
  [
    "src/account_unlink.js~unlinkfacebookrequest#constructor",
    "class/src/account_unlink.js~UnlinkFacebookRequest.html#instance-constructor-constructor",
    "src/account_unlink.js~UnlinkFacebookRequest#constructor",
    "method"
  ],
  [
    "src/account_unlink.js~unlinkgooglerequest#constructor",
    "class/src/account_unlink.js~UnlinkGoogleRequest.html#instance-constructor-constructor",
    "src/account_unlink.js~UnlinkGoogleRequest#constructor",
    "method"
  ],
  [
    "src/account_unlink.js~unlinkrequest#constructor",
    "class/src/account_unlink.js~UnlinkRequest.html#instance-constructor-constructor",
    "src/account_unlink.js~UnlinkRequest#constructor",
    "method"
  ],
  [
    "src/account_unlink.js~unlinktangorequest#constructor",
    "class/src/account_unlink.js~UnlinkTangoRequest.html#instance-constructor-constructor",
    "src/account_unlink.js~UnlinkTangoRequest#constructor",
    "method"
  ],
  [
    "src/achievement.js",
    "file/src/achievement.js.html",
    "src/achievement.js",
    "file"
  ],
  [
    "src/achievement.js~achievementlistrequest#constructor",
    "class/src/achievement.js~AchievementListRequest.html#instance-constructor-constructor",
    "src/achievement.js~AchievementListRequest#constructor",
    "method"
  ],
  [
    "src/achievement.js~achievementlistrequest#session",
    "class/src/achievement.js~AchievementListRequest.html#instance-method-session",
    "src/achievement.js~AchievementListRequest#session",
    "method"
  ],
  [
    "src/achievement.js~achievementupdaterequest#constructor",
    "class/src/achievement.js~AchievementUpdateRequest.html#instance-constructor-constructor",
    "src/achievement.js~AchievementUpdateRequest#constructor",
    "method"
  ],
  [
    "src/client.js",
    "file/src/client.js.html",
    "src/client.js",
    "file"
  ],
  [
    "src/client.js~client#constructor",
    "class/src/client.js~Client.html#instance-constructor-constructor",
    "src/client.js~Client#constructor",
    "method"
  ],
  [
    "src/client.js~client#execute",
    "class/src/client.js~Client.html#instance-method-execute",
    "src/client.js~Client#execute",
    "method"
  ],
  [
    "src/client.js~client#setaccountsserver",
    "class/src/client.js~Client.html#instance-method-setAccountsServer",
    "src/client.js~Client#setAccountsServer",
    "method"
  ],
  [
    "src/client.js~client#setapiserver",
    "class/src/client.js~Client.html#instance-method-setApiServer",
    "src/client.js~Client#setApiServer",
    "method"
  ],
  [
    "src/client.js~response#body",
    "class/src/client.js~Response.html#instance-member-body",
    "src/client.js~Response#body",
    "member"
  ],
  [
    "src/client.js~response#constructor",
    "class/src/client.js~Response.html#instance-constructor-constructor",
    "src/client.js~Response#constructor",
    "method"
  ],
  [
    "src/client.js~response#message",
    "class/src/client.js~Response.html#instance-member-message",
    "src/client.js~Response#message",
    "member"
  ],
  [
    "src/client.js~response#request",
    "class/src/client.js~Response.html#instance-member-request",
    "src/client.js~Response#request",
    "member"
  ],
  [
    "src/client.js~response#status",
    "class/src/client.js~Response.html#instance-member-status",
    "src/client.js~Response#status",
    "member"
  ],
  [
    "src/client.js~response#xhr",
    "class/src/client.js~Response.html#instance-member-xhr",
    "src/client.js~Response#xhr",
    "member"
  ],
  [
    "src/game.js",
    "file/src/game.js.html",
    "src/game.js",
    "file"
  ],
  [
    "src/game.js~gamegetrequest#constructor",
    "class/src/game.js~GameGetRequest.html#instance-constructor-constructor",
    "src/game.js~GameGetRequest#constructor",
    "method"
  ],
  [
    "src/gamer.js",
    "file/src/gamer.js.html",
    "src/gamer.js",
    "file"
  ],
  [
    "src/gamer.js~gamergetrequest#constructor",
    "class/src/gamer.js~GamerGetRequest.html#instance-constructor-constructor",
    "src/gamer.js~GamerGetRequest#constructor",
    "method"
  ],
  [
    "src/gamer.js~gamerupdaterequest#constructor",
    "class/src/gamer.js~GamerUpdateRequest.html#instance-constructor-constructor",
    "src/gamer.js~GamerUpdateRequest#constructor",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/leaderboard.js",
    "file/src/leaderboard.js.html",
    "src/leaderboard.js",
    "file"
  ],
  [
    "src/leaderboard.js~leaderboardandrankgetrequest#autooffset",
    "class/src/leaderboard.js~LeaderboardAndRankGetRequest.html#instance-method-autoOffset",
    "src/leaderboard.js~LeaderboardAndRankGetRequest#autoOffset",
    "method"
  ],
  [
    "src/leaderboard.js~leaderboardandrankgetrequest#constructor",
    "class/src/leaderboard.js~LeaderboardAndRankGetRequest.html#instance-constructor-constructor",
    "src/leaderboard.js~LeaderboardAndRankGetRequest#constructor",
    "method"
  ],
  [
    "src/leaderboard.js~leaderboardgetrequest#constructor",
    "class/src/leaderboard.js~LeaderboardGetRequest.html#instance-constructor-constructor",
    "src/leaderboard.js~LeaderboardGetRequest#constructor",
    "method"
  ],
  [
    "src/leaderboard.js~leaderboardgetrequest#limit",
    "class/src/leaderboard.js~LeaderboardGetRequest.html#instance-method-limit",
    "src/leaderboard.js~LeaderboardGetRequest#limit",
    "method"
  ],
  [
    "src/leaderboard.js~leaderboardgetrequest#offset",
    "class/src/leaderboard.js~LeaderboardGetRequest.html#instance-method-offset",
    "src/leaderboard.js~LeaderboardGetRequest#offset",
    "method"
  ],
  [
    "src/leaderboard.js~leaderboardgetrequest#withscoretags",
    "class/src/leaderboard.js~LeaderboardGetRequest.html#instance-method-withScoretags",
    "src/leaderboard.js~LeaderboardGetRequest#withScoretags",
    "method"
  ],
  [
    "src/leaderboard.js~leaderboardlistrequest#constructor",
    "class/src/leaderboard.js~LeaderboardListRequest.html#instance-constructor-constructor",
    "src/leaderboard.js~LeaderboardListRequest#constructor",
    "method"
  ],
  [
    "src/leaderboard.js~leaderboardupdaterequest#constructor",
    "class/src/leaderboard.js~LeaderboardUpdateRequest.html#instance-constructor-constructor",
    "src/leaderboard.js~LeaderboardUpdateRequest#constructor",
    "method"
  ],
  [
    "src/leaderboard.js~leaderboardupdaterequest#scoretags",
    "class/src/leaderboard.js~LeaderboardUpdateRequest.html#instance-method-scoretags",
    "src/leaderboard.js~LeaderboardUpdateRequest#scoretags",
    "method"
  ],
  [
    "src/match.js",
    "file/src/match.js.html",
    "src/match.js",
    "file"
  ],
  [
    "src/match.js~matchcreaterequest#addfilter",
    "class/src/match.js~MatchCreateRequest.html#instance-method-addFilter",
    "src/match.js~MatchCreateRequest#addFilter",
    "method"
  ],
  [
    "src/match.js~matchcreaterequest#addgamer",
    "class/src/match.js~MatchCreateRequest.html#instance-method-addGamer",
    "src/match.js~MatchCreateRequest#addGamer",
    "method"
  ],
  [
    "src/match.js~matchcreaterequest#constructor",
    "class/src/match.js~MatchCreateRequest.html#instance-constructor-constructor",
    "src/match.js~MatchCreateRequest#constructor",
    "method"
  ],
  [
    "src/match.js~matchgetrequest#constructor",
    "class/src/match.js~MatchGetRequest.html#instance-constructor-constructor",
    "src/match.js~MatchGetRequest#constructor",
    "method"
  ],
  [
    "src/match.js~matchlistrequest#constructor",
    "class/src/match.js~MatchListRequest.html#instance-constructor-constructor",
    "src/match.js~MatchListRequest#constructor",
    "method"
  ],
  [
    "src/match.js~matchmakerequest#addfilter",
    "class/src/match.js~MatchMakeRequest.html#instance-method-addFilter",
    "src/match.js~MatchMakeRequest#addFilter",
    "method"
  ],
  [
    "src/match.js~matchmakerequest#constructor",
    "class/src/match.js~MatchMakeRequest.html#instance-constructor-constructor",
    "src/match.js~MatchMakeRequest#constructor",
    "method"
  ],
  [
    "src/match.js~matchturnendrequest#constructor",
    "class/src/match.js~MatchTurnEndRequest.html#instance-constructor-constructor",
    "src/match.js~MatchTurnEndRequest#constructor",
    "method"
  ],
  [
    "src/match.js~matchturngetrequest#constructor",
    "class/src/match.js~MatchTurnGetRequest.html#instance-constructor-constructor",
    "src/match.js~MatchTurnGetRequest#constructor",
    "method"
  ],
  [
    "src/match.js~matchturnleaverequest#constructor",
    "class/src/match.js~MatchTurnLeaveRequest.html#instance-constructor-constructor",
    "src/match.js~MatchTurnLeaveRequest#constructor",
    "method"
  ],
  [
    "src/match.js~matchturnsubmitrequest#constructor",
    "class/src/match.js~MatchTurnSubmitRequest.html#instance-constructor-constructor",
    "src/match.js~MatchTurnSubmitRequest#constructor",
    "method"
  ],
  [
    "src/match.js~matchessincerequest#constructor",
    "class/src/match.js~MatchesSinceRequest.html#instance-constructor-constructor",
    "src/match.js~MatchesSinceRequest#constructor",
    "method"
  ],
  [
    "src/message.js",
    "file/src/message.js.html",
    "src/message.js",
    "file"
  ],
  [
    "src/message.js~messagedeleterequest#constructor",
    "class/src/message.js~MessageDeleteRequest.html#instance-constructor-constructor",
    "src/message.js~MessageDeleteRequest#constructor",
    "method"
  ],
  [
    "src/message.js~messagelistrequest#constructor",
    "class/src/message.js~MessageListRequest.html#instance-constructor-constructor",
    "src/message.js~MessageListRequest#constructor",
    "method"
  ],
  [
    "src/message.js~messagelistrequest#since",
    "class/src/message.js~MessageListRequest.html#instance-method-since",
    "src/message.js~MessageListRequest#since",
    "method"
  ],
  [
    "src/message.js~messagelistrequest#withbody",
    "class/src/message.js~MessageListRequest.html#instance-method-withBody",
    "src/message.js~MessageListRequest#withBody",
    "method"
  ],
  [
    "src/message.js~messagereadrequest#constructor",
    "class/src/message.js~MessageReadRequest.html#instance-constructor-constructor",
    "src/message.js~MessageReadRequest#constructor",
    "method"
  ],
  [
    "src/message.js~messagereadrequest#withnobody",
    "class/src/message.js~MessageReadRequest.html#instance-method-withNoBody",
    "src/message.js~MessageReadRequest#withNoBody",
    "method"
  ],
  [
    "src/ping.js",
    "file/src/ping.js.html",
    "src/ping.js",
    "file"
  ],
  [
    "src/ping.js~pingrequest#constructor",
    "class/src/ping.js~PingRequest.html#instance-constructor-constructor",
    "src/ping.js~PingRequest#constructor",
    "method"
  ],
  [
    "src/ping.js~pingrequest#session",
    "class/src/ping.js~PingRequest.html#instance-method-session",
    "src/ping.js~PingRequest#session",
    "method"
  ],
  [
    "src/request.js",
    "file/src/request.js.html",
    "src/request.js",
    "file"
  ],
  [
    "src/request.js~accountsrequest#constructor",
    "class/src/request.js~AccountsRequest.html#instance-constructor-constructor",
    "src/request.js~AccountsRequest#constructor",
    "method"
  ],
  [
    "src/request.js~apirequest#constructor",
    "class/src/request.js~ApiRequest.html#instance-constructor-constructor",
    "src/request.js~ApiRequest#constructor",
    "method"
  ],
  [
    "src/request.js~request#constructor",
    "class/src/request.js~Request.html#instance-constructor-constructor",
    "src/request.js~Request#constructor",
    "method"
  ],
  [
    "src/script.js",
    "file/src/script.js.html",
    "src/script.js",
    "file"
  ],
  [
    "src/script.js~executescriptrequest#constructor",
    "class/src/script.js~ExecuteScriptRequest.html#instance-constructor-constructor",
    "src/script.js~ExecuteScriptRequest#constructor",
    "method"
  ],
  [
    "src/script.js~executescriptrequest#data",
    "class/src/script.js~ExecuteScriptRequest.html#instance-method-data",
    "src/script.js~ExecuteScriptRequest#data",
    "method"
  ],
  [
    "src/script.js~executescriptrequest#session",
    "class/src/script.js~ExecuteScriptRequest.html#instance-method-session",
    "src/script.js~ExecuteScriptRequest#session",
    "method"
  ],
  [
    "src/server.js",
    "file/src/server.js.html",
    "src/server.js",
    "file"
  ],
  [
    "src/server.js~serverrequest#constructor",
    "class/src/server.js~ServerRequest.html#instance-constructor-constructor",
    "src/server.js~ServerRequest#constructor",
    "method"
  ],
  [
    "src/session.js",
    "file/src/session.js.html",
    "src/session.js",
    "file"
  ],
  [
    "src/session.js~session#constructor",
    "class/src/session.js~Session.html#instance-constructor-constructor",
    "src/session.js~Session#constructor",
    "method"
  ],
  [
    "src/shared_storage.js",
    "file/src/shared_storage.js.html",
    "src/shared_storage.js",
    "file"
  ],
  [
    "src/shared_storage.js~sharedstoragedeleterequest#constructor",
    "class/src/shared_storage.js~SharedStorageDeleteRequest.html#instance-constructor-constructor",
    "src/shared_storage.js~SharedStorageDeleteRequest#constructor",
    "method"
  ],
  [
    "src/shared_storage.js~sharedstoragegetrequest#constructor",
    "class/src/shared_storage.js~SharedStorageGetRequest.html#instance-constructor-constructor",
    "src/shared_storage.js~SharedStorageGetRequest#constructor",
    "method"
  ],
  [
    "src/shared_storage.js~sharedstoragepatchrequest#constructor",
    "class/src/shared_storage.js~SharedStoragePatchRequest.html#instance-constructor-constructor",
    "src/shared_storage.js~SharedStoragePatchRequest#constructor",
    "method"
  ],
  [
    "src/shared_storage.js~sharedstorageputrequest#constructor",
    "class/src/shared_storage.js~SharedStoragePutRequest.html#instance-constructor-constructor",
    "src/shared_storage.js~SharedStoragePutRequest#constructor",
    "method"
  ],
  [
    "src/shared_storage.js~sharedstoragesearchrequest#constructor",
    "class/src/shared_storage.js~SharedStorageSearchRequest.html#instance-constructor-constructor",
    "src/shared_storage.js~SharedStorageSearchRequest#constructor",
    "method"
  ],
  [
    "src/shared_storage.js~sharedstoragesearchrequest#filterkey",
    "class/src/shared_storage.js~SharedStorageSearchRequest.html#instance-method-filterKey",
    "src/shared_storage.js~SharedStorageSearchRequest#filterKey",
    "method"
  ],
  [
    "src/shared_storage.js~sharedstoragesearchrequest#limit",
    "class/src/shared_storage.js~SharedStorageSearchRequest.html#instance-method-limit",
    "src/shared_storage.js~SharedStorageSearchRequest#limit",
    "method"
  ],
  [
    "src/shared_storage.js~sharedstoragesearchrequest#offset",
    "class/src/shared_storage.js~SharedStorageSearchRequest.html#instance-method-offset",
    "src/shared_storage.js~SharedStorageSearchRequest#offset",
    "method"
  ],
  [
    "src/shared_storage.js~sharedstoragesearchrequest#sort",
    "class/src/shared_storage.js~SharedStorageSearchRequest.html#instance-method-sort",
    "src/shared_storage.js~SharedStorageSearchRequest#sort",
    "method"
  ],
  [
    "src/storage.js",
    "file/src/storage.js.html",
    "src/storage.js",
    "file"
  ],
  [
    "src/storage.js~storagedeleterequest#constructor",
    "class/src/storage.js~StorageDeleteRequest.html#instance-constructor-constructor",
    "src/storage.js~StorageDeleteRequest#constructor",
    "method"
  ],
  [
    "src/storage.js~storagegetrequest#constructor",
    "class/src/storage.js~StorageGetRequest.html#instance-constructor-constructor",
    "src/storage.js~StorageGetRequest#constructor",
    "method"
  ],
  [
    "src/storage.js~storageputrequest#constructor",
    "class/src/storage.js~StoragePutRequest.html#instance-constructor-constructor",
    "src/storage.js~StoragePutRequest#constructor",
    "method"
  ]
]